### ISSUE TITLE
ImportError: cannot import name 'PackageFinder' from 'pip._internal.index'

### ISSUE THREAD

**Issue by trierweiler** [riken-aip/pyHSICLasso#37]
Hi,

When trying to install the package in Anaconda, through pip or directly from setup.py, it throws the following error:

ImportError: cannot import name 'PackageFinder' from 'pip._internal.index'

**Comment by myamada0321** [comment]
Thanks for the feedback.

Could you give us a bit more information?  For example, the Python version and the Anaconda version. For my environment, I can install it with Python 3.7.6

Thanks

**Comment by trierweiler** [comment]
Hi,

Thank you for your email.
My python version is the same as yours 3.7.6 and Anaconda is 1.9.12.

When trying to install in Anaconda prompt it returns the following error:

(base) C:\WINDOWS\system32>pip install pyHSICLasso
Traceback (most recent call last):
  File "C:\Users\eng_g\anaconda3\Scripts\pip-script.py", line 10, in
<module>
    sys.exit(main())
  File "C:\Users\eng_g\anaconda3\lib\site-packages\pip\_internal\main.py",
line 45, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File
"C:\Users\eng_g\anaconda3\lib\site-packages\pip\_internal\commands\__init__.py",
line 96, in create_command
    module = importlib.import_module(module_path)
  File "C:\Users\eng_g\anaconda3\lib\importlib\__init__.py", line 127, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in
_call_with_frames_removed
  File
"C:\Users\eng_g\anaconda3\lib\site-packages\pip\_internal\commands\install.py",
line 23, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File
"C:\Users\eng_g\anaconda3\lib\site-packages\pip\_internal\cli\req_command.py",
line 17, in <module>
    from pip._internal.index import PackageFinder
ImportError: cannot import name 'PackageFinder' from 'pip._internal.index'
(C:\Users\eng_g\anaconda3\lib\site-packages\pip\_internal\index\__init__.py)

Regards,
Gabriel

**Comment by hclimente** [comment]
Hi,

I was not able to replicate the issue either. From what I read [elsewhere](https://stackoverflow.com/questions/59887436/importerror-cannot-import-name-packagefinder), this seems to be an issue with the pip environment, and so re-installing pip often helps.

Best regards,
Héctor.
