### ISSUE TITLE
Is there a way to extract the predicted value of the trained HSIC Lasso (Regression)?

### ISSUE THREAD

**Issue by srivas53** [riken-aip/pyHSICLasso#44]
After HSIC Lasso (Regression) has finished executing, we will have the beta values for every feature in the training dataset. Therefore, is there a way to determine the predicted value of a given instance? I am trying to evaluate the model fit via mean squared error, as done in the original paper (_High-Dimensional Feature Selection by Feature-Wise Kernelized Lasso_, Section 4.3.2)

**Comment by mattrmd** [comment]
@srivas53 My understanding is that the authors did not "extract the predicted value of the trained HSIC LASSO" model. Instead, they trained a new model on the features selected by the HSIC model:

> We use **kernel regression (KR) with the Gaussian kernel** for evaluating the mean squared error and the mean correlation when the top $m = 10, 20, ..., 50$ features selected by each method [(including HSIC)] are used. We first choose $50$ features and then use top $m = 10, 20, ..., 50$ features having the largest absolute regression coefficients.

EDIT: If you want to get the features that are selected by HSIC, you can get the indices of the selected features using
```python
# ...
hsic_lasso = HSICLasso()

hsic_lasso.input(x_train, y_train)
hsic_lasso.regression(5)

sel_feats = hsic_lasso.get_index()
```

**Comment by hclimente** [comment]
That's correct, @mattrmd. Thanks for your contribution.
